"""Creating rentals table

Revision ID: e081116a8b97
Revises: 819d611920e8
Create Date: 2026-01-09 13:18:23.999875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e081116a8b97'
down_revision = '819d611920e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=30), nullable=True),
    sa.Column('person_surname', sa.String(length=30), nullable=True),
    sa.Column('item_name', sa.String(length=30), nullable=True),
    sa.Column('item_category', sa.String(length=30), nullable=True),
    sa.Column('item_localization', sa.String(length=30), nullable=True),
    sa.Column('item_amount', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    # ### end Alembic commands ###
